
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnjupqmgixtvjewkzjnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduanVwcW1naXh0dmpld2t6am53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjA5MzgsImV4cCI6MjA1ODMzNjkzOH0.O6y_5SEc-HarfepaY_cW7N6uhKa3_85hOioh33tIHrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      // Set the site URL to gaganahuja.com
      site: 'https://www.gaganahuja.com',
      // Set the redirect URL to gaganahuja.com
      redirectTo: 'https://www.gaganahuja.com',
    }
  }
);
